/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "error-container": "#93000a",
        "tertiary-container": "#46d89d",
        "inverse-on-surface": "#2b303d",
        "primary-container": "#22d3ee",
        "surface-variant": "#2f3542",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#001f25",
        "primary-fixed": "#a2eeff",
        "secondary-fixed": "#e1e0ff",
        "on-error": "#690005",
        "surface-container-highest": "#2f3542",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-container": "#b0b2ff",
        "on-secondary-fixed": "#07006c",
        "outline-variant": "#3c494c",
        "outline": "#859397",
        "on-error-container": "#ffdad6",
        "primary": "#8aebff",
        "surface-bright": "#343946",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#242a36",
        "on-background": "#dde2f3",
        "on-tertiary-fixed": "#002113",
        "background": "#0e131f",
        "secondary": "#c0c1ff",
        "on-primary-fixed-variant": "#004e5a",
        "on-primary": "#00363e",
        "inverse-surface": "#dde2f3",
        "tertiary": "#68f5b8",
        "surface-container-low": "#161c28",
        "on-surface": "#dde2f3",
        "on-primary-container": "#005763",
        "surface-tint": "#2fd9f4",
        "on-tertiary": "#003824",
        "tertiary-fixed": "#6ffbbe",
        "on-surface-variant": "#bbc9cd",
        "on-tertiary-container": "#005a3d",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "surface": "#0e131f",
        "surface-dim": "#0e131f",
        "surface-container-lowest": "#080e1a",
        "surface-container": "#1a202c",
        "inverse-primary": "#006877",
        "primary-fixed-dim": "#2fd9f4"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "unit": "4px",
        "stack-md": "16px",
        "container-padding-mobile": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-padding-desktop": "40px"
      },
      "fontFamily": {
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "0", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "0", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "0", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
