apiVersion: apps/v1
kind: Deployment
metadata:
  name: breathe-safe-frontend
  labels:
    app: breathe-safe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breathe-safe-frontend
  template:
    metadata:
      labels:
        app: breathe-safe-frontend
    spec:
      containers:
        - name: frontend
          image: breathe-safe-ai-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: breathe-safe-frontend
spec:
  type: ClusterIP
  selector:
    app: breathe-safe-frontend
  ports:
    - port: 80
      targetPort: 80
